apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-web-app
  labels:
    app: document-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: document-web-app
  template:
    metadata:
      name: document-web-app
      labels:
        app: document-web-app
    spec:
      containers:
        - name: document-web-app
          image: docker.io/dyamo/document-web-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-user
                  key: connectionString.standardSrv
            - name: DATABASE_NAME
              value: document-web-app
            - name: COLLECTION_NAME
              value: documents
